---
title: "32968282_JasonMoffat_Nature_2020"
author: "BuilderPie"
date: "2021-02-05"
output: 
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Condition alignment

```{r, message=FALSE, warning=FALSE}
library(workflowr)
library(GEOquery)
library(ggfortify)
library(ComplexHeatmap)
library(circlize)

gse = getGEO(filename="data/32968282_JasonMoffat_Nature_2020/GSE149933-GPL17021_series_matrix.txt.gz",GSEMatrix=TRUE,getGPL = FALSE)
dir.create("output/32968282_JasonMoffat_Nature_2020", recursive = T, showWarnings = F)
write.table(gse, 'output/32968282_JasonMoffat_Nature_2020/GPL17021.txt', quote = F, sep = '\t', col.names = T)
meta_GPL17021 = read.table('output/32968282_JasonMoffat_Nature_2020/GPL17021.txt', stringsAsFactors = F, sep = '\t', row.names = 1)

gse = getGEO(filename="data/32968282_JasonMoffat_Nature_2020/GSE149933-GPL19057_series_matrix.txt.gz",GSEMatrix=TRUE,getGPL = FALSE)
# dir.create("output/32968282_JasonMoffat_Nature_2020", recursive = T, showWarnings = F)
write.table(gse, 'output/32968282_JasonMoffat_Nature_2020/GPL19057.txt', quote = F, sep = '\t', col.names = T)
meta_GPL19057 = read.table('output/32968282_JasonMoffat_Nature_2020/GPL19057.txt', stringsAsFactors = F, sep = '\t', row.names = 1)

treatment_GPL17021 = meta_GPL17021$characteristics_ch1.1
treatment_GPL17021[grep('Control',treatment_GPL17021, ignore.case = T)]="_Con"
treatment_GPL17021[grep('T cell',treatment_GPL17021, ignore.case = T)]="_T"
treatment_GPL17021[grep('none',treatment_GPL17021, ignore.case = T)]="_none"
treatment_GPL17021[grep('IFN-gamma',treatment_GPL17021, ignore.case = T)]="_IFNg"
treatment_GPL17021[grep('TNF-alpha',treatment_GPL17021, ignore.case = T)]="_TNFa"

treatment_GPL19057 = meta_GPL19057$characteristics_ch1.1
treatment_GPL19057[grep('Control',treatment_GPL19057, ignore.case = T)]="_Con"
treatment_GPL19057[grep('T cell',treatment_GPL19057, ignore.case = T)]="_T"
treatment_GPL19057[grep('none',treatment_GPL19057, ignore.case = T)]="_none"
treatment_GPL19057[grep('IFN-gamma',treatment_GPL19057, ignore.case = T)]="_IFNg"
treatment_GPL19057[grep('TNF-alpha',treatment_GPL19057, ignore.case = T)]="_TNFa"


title_comb = c(paste0(meta_GPL17021$title, treatment_GPL17021), 
               paste0(meta_GPL19057$title, treatment_GPL19057))

print(meta_GPL17021[1:14,c("title","source_name_ch1", "characteristics_ch1.1", "time.point.ch1")])

rawCount = read.table(file = "data/32968282_JasonMoffat_Nature_2020/GSE149933_mTKO_readCounts_4May20.txt", header = T)
title_comb = gsub(" ", "_", title_comb)
title_trim = sub("^([^_]*_[^_]*).*", "\\1", title_comb)
colName = colnames(rawCount)
finalCount = c()
for (i in 1:length(colName)){
  ind = which(title_trim == colName[i])
  if (length(ind)>0){
    # print(ind)
    # print(colName[i])
    # print(title_trim[ind])
    finalCount = cbind(finalCount, rawCount[,i])
    colnames(finalCount)[dim(finalCount)[2]] = sub("^([^_]*_[^_]*).", "", title_comb[ind])
    # print(title_comb[ind])
    # print(colnames(finalCount)[dim(finalCount)[2]])
  }
}
finalCount = as.data.frame(finalCount)
finalCount_output = cbind(rawCount[,6:7], finalCount)
colnames(finalCount_output)[1:2] = c("Gene", "sgRNA")
dir.create("../run_MAGeCK-VISPR_output/32968282_JasonMoffat_Nature_2020", recursive = T, showWarnings = F)
write.table(x = finalCount_output, file = '../run_MAGeCK-VISPR_output/32968282_JasonMoffat_Nature_2020/32968282_JasonMoffat_Nature_2020_rawcount.txt', quote = F, sep = '\t', col.names = T)
finalCount = log(finalCount + 1)

cellline = c("EMT6-HA_", "CT26-HA_", "4T1-HA_", "B16-Ova_", "MC38-Ova_", "Renca-HA_")
for (cl in cellline){
  # print(cl)
  df = as.data.frame(t(finalCount[, grep(cl, colnames(finalCount))]))
  pca_res <- prcomp(df)
  df$condition = sapply(X = strsplit(rownames(df),"_"), FUN = function(x){x[4]})
  df$batch = sapply(X = strsplit(rownames(df),"_"), FUN = function(x){x[3]})
  # df[ , which(apply(df, 2, var) != 0)]
  # pca_res <- prcomp(df[,-dim(df)[2]], scale. = TRUE)
  # print(autoplot(pca_res, data = df, colour = 'species', label = TRUE, label.size = 4, 
                 # xlim = c((1.3*min(pca_res$rotation[,'PC1'],na.rm=T)-0.3*max(min(pca_res$rotation[,'PC1'],na.rm=T))),
                 #          (1.3*max(pca_res$rotation[,'PC1'],na.rm=T)-0.3*min(pca_res$rotation[,'PC1'],na.rm=T))), 
                 # ylim = c((1.3*min(pca_res$rotation[,'PC2'],na.rm=T)-0.3*max(min(pca_res$rotation[,'PC2'],na.rm=T))),
                 #          (1.3*max(pca_res$rotation[,'PC2'],na.rm=T)-0.3*min(pca_res$rotation[,'PC2'],na.rm=T))),
                 # main = paste0(cl, "PCA")))
  
  print(autoplot(pca_res, data = df, colour = 'condition', shape = "batch", size = 5, main = paste0(cl, "PCA")))
  
  cor_res = cor(t(df[, -which(colnames(df)=="condition" | colnames(df)=="batch")]))
  print(Heatmap(cor_res, col = colorRamp2(c(min(cor_res, na.rm = T), 1), c("white", "red")),
          column_title = paste0(cl, "Correlation")))
  
  df = df[-grep("_T0_", rownames(df)), ]
  pca_res <- prcomp(df[, -which(colnames(df)=="condition" | colnames(df)=="batch")])
  print(autoplot(pca_res, data = df, colour = 'condition', shape = "batch", size = 5, main = paste0(cl, "wo_T0")))
  
  cor_res = cor(t(df[, -which(colnames(df)=="condition" | colnames(df)=="batch")]))
  print(Heatmap(cor_res, col = colorRamp2(c(min(cor_res, na.rm = T), 1), c("white", "red")),
          column_title = paste0(cl, "wo_T0_Correlation")))
}

```

```{r MAGEcK-VISPR, engine='bash', eval=FALSE}
conda activate mageck-vispr
cd ~/Tigger/Tigger/prepare_data/otherPreprocessing/Crispr/

# change step1_run_mageck_vispr.R Line 243 from
# runmageckvispr(annfile = annfile, run = c("rra"), study = NULL, countFolder = '/liulab/zzeng/Tigger/static/data/Crispr/rawCount', dryrun = FALSE)
# to
# runmageckvispr(annfile = annfile, run = c("rra"), study = '32968282_JasonMoffat_Nature_2020', countFolder = '/liulab/zzeng/Tigger/static/data/Crispr/rawCount', dryrun = FALSE)
Rscript step1_run_mageck_vispr.R
```