---
title: "MAGeCK-VISPR Quality Check"
author: "Dian Li, Wubing Zhang, Davis Zexian Zeng"
site: workflowr::wflow_site
date: "`r Sys.Date()`"
output: 
  workflowr::wflow_html:
    toc: true
    number_sections: true
    toc_depth: 2
    df_print: paged
    css: style.css
    toc_float:
      collapsed: false
      smooth_scroll: true
editor_options:
  chunk_output_type: console
description: "This document contains quality check (QC) results for running MAGeCK-VISPR 'test' module on CRISPR data."
---

# Introduction

This document contains quality check (QC) results from running **MAGeCK-VISPR** _test_ module on immune-related CRISPR data. We have annotated the results into four major categories: **Coculture screens**, **Essentiality screens**, **In-vivo screens**, and **Sorting screens**. 

---

# Coculture screens

## Coculture-NK

1. <a href="01-coculture.html#"></a>

---

## Coculture-T

1. <a href="01-coculture.html#1_28783722_|_NicholasPRestifo_|_Nature_|_2017_|_Mel624_|_EffectT">28783722 | NicholasPRestifo | Nature | 2017 | Mel624 | EffectT</a>
2. <a href="01-coculture.html#2_29301958_|_KaiWWucherpfennig_|_Science_|_2018_|_B16F10_|_OT-IOVA">29301958 | KaiWWucherpfennig | Science | 2018 | B16F10 | OT-I.OVA</a>
3. <a href="01-coculture.html#4_32968282_|_JasonMoffat_|_Nature_|_2020_|_4T1-HA_|_CL4">32968282 | JasonMoffat | Nature | 2020 | 4T1-HA | CL4</a>
4. <a href="01-coculture.html#5_32968282_|_JasonMoffat_|_Nature_|_2020_|_B16-OVA_|_OT-I">32968282 | JasonMoffat | Nature | 2020 | B16-OVA | OT-I</a>
5. <a href="01-coculture.html#6_32968282_|_JasonMoffat_|_Nature_|_2020_|_CT26-HA_|_CL4">6_32968282_|_JasonMoffat_|_Nature_|_2020_|_CT26-HA_|_CL4</a>
6. <a href="01-coculture.html#7_32968282_|_JasonMoffat_|_Nature_|_2020_|_EMT6-HA_|_CL4">7_32968282_|_JasonMoffat_|_Nature_|_2020_|_EMT6-HA_|_CL4</a>
7. <a href="01-coculture.html#8_32968282_|_JasonMoffat_|_Nature_|_2020_|_MC38-OVA_|_OT-I">32968282 | JasonMoffat | Nature | 2020 | MC38-OVA | OT-I</a>
8. <a href="01-coculture.html#9_32968282_|_JasonMoffat_|_Nature_|_2020_|_Renca-HA_|_CL4">32968282 | JasonMoffat | Nature | 2020 | Renca-HA | CL4</a>


---

# Essentiality screens

1. <a href="02-essentiality.html#"></a>

---

# In-vivo screens

1. <a href="03-invivo.html#2_28723893_|_WNicholasHaining_|_Nature_|_2017_|_B16F10_|_GVAX+aPD1">28723893 | WNicholasHaining | Nature | 2017 | B16F10 | GVAX+aPD1</a>
2. <a href="03-invivo.html#3_28723893_|_WNicholasHaining_|_Nature_|_2017_|_B16F10_|_GVAX">28723893 | WNicholasHaining | Nature | 2017 | B16F10 | GVAX</a>
3. <a href="03-invivo.html#4_28723893_|_WNicholasHaining_|_Nature_|_2017_|_B16F10_|_koTCRa">28723893 | WNicholasHaining | Nature | 2017 | B16F10 | koTCRa</a>
4. <a href="03-invivo.html#5_33497609_|_RobertTManguso_|_Immunity_|_2021_|_Renca_|_aPD1+aCTLA4">33497609 | RobertTManguso | Immunity | 2021 | Renca | aPD1+aCTLA4</a>

---

# Sorting screens

1. <a href="04-sorting.html#2_26189680_|_AvivRegev_|_Cell_|_2015_|_BMDCs_|_TNF">26189680 | AvivRegev | Cell | 2015 | BMDCs | TNF</a>
2. <a href="04-sorting.html#3_28813417_|_MarkADawson_|_Nature_|_2017_|_BxPC-3_|_PD-L1">28813417 | MarkADawson | Nature | 2017 | BxPC-3 | PD-L1</a>
3. <a href="04-sorting.html#4_33271120_|_JonathanWYewdell_|_Immunity_|_2021_|_BJAB_|_MHCI">33271120 | JonathanWYewdell | Immunity | 2021 | BJAB | MHCI</a>
4. <a href="04-sorting.html#5_33271120_|_JonathanWYewdell_|_Immunity_|_2021_|_HBL1_|_MHCI">33271120 | JonathanWYewdell | Immunity | 2021 | HBL1 | MHCI</a>
5. <a href="04-sorting.html#6_33271120_|_JonathanWYewdell_|_Immunity_|_2021_|_SUDHL5_|_MHCI">33271120 | JonathanWYewdell | Immunity | 2021 | SUDHL5 | MHCI</a>
6. <a href="04-sorting.html#7_33271120_|_JonathanWYewdell_|_Immunity_|_2021_|_TMD8_|_MHCI">33271120 | JonathanWYewdell | Immunity | 2021 | TMD8 | MHCI</a>
7. <a href="04-sorting.html#8_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M1negScreenMHCIhigh">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M1.negScreen.MHCI.high</a>
8. <a href="04-sorting.html#9_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M2negScreenMHCIhigh">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M2.negScreen.MHCI.high</a>
9. <a href="04-sorting.html#10_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M1negScreenMHCIhigh+PDL1high">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M1.negScreen.MHCI.high+PDL1.high</a>
10. <a href="04-sorting.html#11_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M2negScreenMHCIhigh+PDL1high">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M2.negScreen.MHCI.high+PDL1.high</a>
11. <a href="04-sorting.html#12_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M1negScreenPDL1high">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M1.negScreen.PDL1.high</a>
12. <a href="04-sorting.html#13_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M2negScreenPDL1high">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M2.negScreen.PDL1.high</a>
13. <a href="04-sorting.html#14_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M1posScreenMHCIlow">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M1.posScreen.MHCI.low</a>
14. <a href="04-sorting.html#15_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M2posScreenMHCIlow">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M2.posScreen.MHCI.low</a>
15. <a href="04-sorting.html#16_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M1posScreenMHCIlow+PDL1low">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M1.posScreen.MHCI.low+PDL1.low</a>
16. <a href="04-sorting.html#17_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M2posScreenMHCIlow+PDL1low">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M2.posScreen.MHCI.low+PDL1.low</a>
17. <a href="04-sorting.html#18_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M1posScreenPDL1low">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M1.posScreen.PDL1.low</a>
18. <a href="04-sorting.html#19_33589424_|_XShirleyLiu_|_CancerDiscov_|_2021_|_B16F10_|_M2posScreenPDL1low">33589424 | XShirleyLiu | CancerDiscov | 2021 | B16F10 | M2.posScreen.PDL1.low</a>
19. <a href="04-sorting.html#20_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M1negScreenMHCIIhigh">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M1.negScreen.MHCII.high</a>
20. <a href="04-sorting.html#21_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M2negScreenMHCIIhigh">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M2.negScreen.MHCII.high</a>
21. <a href="04-sorting.html#22_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M1negScreenMHCIIhigh+PDL1high">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M1.negScreen.MHCII.high+PDL1.high</a>
22. <a href="04-sorting.html#23_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M2negScreenMHCIIhigh+PDL1high">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M2.negScreen.MHCII.high+PDL1.high</a>
23. <a href="04-sorting.html#24_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M1negScreenPDL1high">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M1.negScreen.PDL1.high</a>
24. <a href="04-sorting.html#25_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M2negScreenPDL1high">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M2.negScreen.PDL1.high</a>
25. <a href="04-sorting.html#26_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M1posScreenMHCIIlow">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M1.posScreen.MHCII.low</a>
26. <a href="04-sorting.html#27_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M2posScreenMHCIIlow">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M2.posScreen.MHCII.low</a>
27. <a href="04-sorting.html#28_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M1posScreenMHCIIlow+PDL1low">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M1.posScreen.MHCII.low+PDL1.low</a>
28. <a href="04-sorting.html#29_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M2posScreenMHCIIlow+PDL1low">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M2.posScreen.MHCII.low+PDL1.low</a>
29. <a href="04-sorting.html#30_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M1posScreenPDL1low">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M1.posScreen.PDL1.low</a>
30. <a href="04-sorting.html#31_TBD_|_XShirleyLiu_|_TBD_|_2021_|_B16F10_|_M2posScreenPDL1low">TBD | XShirleyLiu | TBD | 2021 | B16F10 | M2.posScreen.PDL1.low</a>


---

# Additional links
1. <a href="https://bitbucket.org/liulab/mageck-vispr/src/master/">MAGeCK-VISPR Installation</a>
2. <a href="https://builderpie.github.io/run_MAGeCK-VISPR/32968282_JasonMoffat_Nature_2020.html">32968282_JasonMoffat_Nature_2020</a>

---
